### ISSUE TITLE
Questions about comparison set in Adversarial training

### ISSUE THREAD

**Issue by ShengleiH** [cookielee77/RankGan-NIPS2017#1]
Hi  @kevinlin311tw @cookielee77 

Thanks for sharing your codes!

I have a questions about calculating rank scores in adversarial train:
When calculating rollout rewards for Generator, there are only fake data (samples generated by Generator) and reference data feed to the Ranker, which is different to the paper. In the paper, to calculate rewards, there should be fake data, **comparison data (real data)** and reference data feed to the Ranker. I am wondering why you didn't feed the **comparison data (real data)** to the Ranker when adversarial training?

Looking forward to your reply~ Thank you!

**Comment by cookielee77** [comment]
Hi, 

We have made several small modifications in this released version. We found including real data in generator training doesn't lead to large performance boosting, but slow down the training process a lot (There is a rollout step in generator training). Thus, we don't includes the real data in generator comparison anymore.
